// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    employee = {
        name: 'John Heart',
        position: 'CEO',
        hireDate: new Date(2012, 4, 13),
        officeNumber: 901,
        phone: '+1(213) 555-9392',
        skype: 'jheart_DX_skype',
        email: 'jheart@dx-email.com',
        notes: 'John has been in the Audio/Video industry since 1990.'
    }

    isFormReadOnly = false

    submitButtonOptions = {
        text: "Submit the Form",
        useSubmitBehavior: true
    }

    handleSubmit = function(e) {
        setTimeout(() => { 
            alert("Submitted");          
        }, 1000);
        
        e.preventDefault();
    }
}
<div id="app-container">
    <form action="/employee-page" (submit)="handleSubmit($event)">
        <dx-form
            id="form"
            [formData]="employee"
            [readOnly]="isFormReadOnly"
            labelLocation="top"
            [showColonAfterLabel]="false">
            <dxi-item 
                itemType="group" 
                [colCount]="2">
                <dxi-item 
                    itemType="group" 
                    caption="Employee">
                    <dxi-item dataField="name" [isRequired]="true"></dxi-item>
                    <dxi-item dataField="position"></dxi-item>
                    <dxi-item dataField="hireDate"></dxi-item>
                    <dxi-item dataField="officeNumber">
                        <dxi-validation-rule
                            type="numeric"
                            message="This field should contain a number">
                        </dxi-validation-rule>
                    </dxi-item>
                </dxi-item>
                <dxi-item itemType="group" caption="Personal Information">
                    <dxi-item itemType="tabbed">
                        <dxo-tab-panel-options [height]="320" [elementAttr]="{ id: 'tabbedItem' }">
                        </dxo-tab-panel-options>
                        <dxi-tab title="Contacts">
                            <dxi-item dataField="skype"></dxi-item>
                            <dxi-item dataField="phone"></dxi-item>
                            <dxi-item dataField="email">
                                <dxi-validation-rule
                                    type="email"
                                    message="This is not a valid Email">
                                </dxi-validation-rule>
                            </dxi-item>
                        </dxi-tab>
                        <dxi-tab title="Note">
                            <dxi-item 
                                dataField="notes"
                                editorType="dxTextArea">
                            </dxi-item>
                        </dxi-tab>
                    </dxi-item>
                </dxi-item>
            </dxi-item>
            <dxi-item 
                itemType="button"
                horizontalAlignment="center"
                [buttonOptions]="submitButtonOptions">
            </dxi-item>
        </dx-form>

        <dx-check-box
            id="check-box"
            text="Enable read-only mode"
            [(value)]="isFormReadOnly">
        </dx-check-box>
    </form>
</div>

// react/src/App.js
import React, { useState, useCallback } from 'react';
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import './App.css'

import Form, { 
  SimpleItem, 
  GroupItem,
  ButtonItem,
  TabbedItem,
  Tab,
  TabPanelOptions,
  NumericRule, 
  EmailRule,
  ButtonOptions
} from 'devextreme-react/form';

import { CheckBox } from 'devextreme-react/check-box';
import 'devextreme-react/text-area';

const employee = {
  name: 'John Heart',
  position: 'CEO',
  hireDate: new Date(2012, 4, 13),
  officeNumber: 901,
  phone: '+1(213) 555-9392',
  skype: 'jheart_DX_skype',
  email: 'jheart@dx-email.com',
  notes: 'John has been in the Audio/Video industry since 1990.'
};

const tabPanelProperties = {
  id: 'tabbedItem'
}

const App = () => {
  const handleSubmit = React.useCallback((e) => {
      setTimeout(() => { 
          alert("Submitted");          
      }, 1000);

      e.preventDefault();
  }, []);

  const [isFormReadOnly, setisFormReadOnly] = useState(false);

  const onCheckBoxValueChanged = useCallback((e) => {
      setisFormReadOnly(e.value);
  }, []);

  return (
    <div id="app-container">
      <form action="/employee-page" onSubmit={handleSubmit}>
        <Form
          id="form"
          formData={employee}
          readOnly={isFormReadOnly}
          labelLocation="top"
          showColonAfterLabel={false}>
          <GroupItem
            colCount={2}>
            <GroupItem caption="Employee">
              <SimpleItem dataField="name" isRequired={true} />
              <SimpleItem dataField="position" />
              <SimpleItem dataField="hireDate" />
              <SimpleItem dataField="officeNumber">
                <NumericRule
                  message="This field should contain a number"
                />
              </SimpleItem>
            </GroupItem>
            <GroupItem caption="Personal Information">
              <TabbedItem>
                <TabPanelOptions
                  height={320} elementAttr={tabPanelProperties}
                />
                <Tab title="Contacts">
                  <SimpleItem dataField="phone" />
                  <SimpleItem dataField="skype" />
                  <SimpleItem dataField="email">
                    <EmailRule
                      message="This is not a valid Email"
                    />
                  </SimpleItem>
                </Tab>
                <Tab title="Note">
                  <SimpleItem 
                    dataField="notes"
                    editorType="dxTextArea"
                  />
                </Tab>
              </TabbedItem>
            </GroupItem>
          </GroupItem>
          <ButtonItem 
            horizontalAlignment="center">
            <ButtonOptions 
              text="Submit the Form"
              useSubmitBehavior={true}
            />
          </ButtonItem>
        </Form>
      </form>

      <CheckBox
        id="check-box"
        text="Enable read-only mode"
        value={isFormReadOnly}
        onValueChanged={onCheckBoxValueChanged}
      />
    </div>
  );
}

export default App;
